import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'pt' | 'en' | 'es' | 'fr' | 'de' | 'it' | 'zh' | 'ja' | 'ko' | 'ru' | 'ar' | 'hi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  pt: {
    // Header
    'nav.features': 'Recursos',
    'nav.about': 'Sobre',
    'nav.contact': 'Contato',
    'auth.login': 'Login',
    'auth.signup': 'Cadastrar',
    'auth.logout': 'Sair',
    'nav.dashboard': 'Dashboard',
    
    // Hero
    'hero.badge': 'Orientação Profissional com IA',
    'hero.title': 'Sua jornada para o',
    'hero.titleHighlight': ' mercado de trabalho ',
    'hero.titleEnd': 'começa aqui',
    'hero.description': 'O NexusAI é seu assistente inteligente para encontrar oportunidades, aprimorar seu currículo e conquistar a vaga dos seus sonhos.',
    'hero.getStarted': 'Começar Agora',
    'hero.demo': 'Ver Demonstração',
    'hero.stat1': 'Jovens Orientados',
    'hero.stat2': 'Taxa de Sucesso',
    'hero.stat3': 'Suporte IA',
    
    // Dashboard
    'dashboard.title': 'Painel de Controle',
    'dashboard.welcome': 'Bem-vindo de volta',
    'dashboard.welcomeBack': 'Bem-vindo de volta',
    'dashboard.resume': 'Otimizar Currículo',
    'dashboard.resumeDesc': 'Crie e otimize seu currículo profissional',
    'dashboard.interview': 'Preparação para Entrevistas',
    'dashboard.interviewDesc': 'Pratique e prepare-se para suas entrevistas',
    'dashboard.skills': 'Desenvolvimento de Habilidades',
    'dashboard.skillsDesc': 'Aprimore suas competências profissionais',
    'dashboard.jobs': 'Buscar Vagas',
    'dashboard.jobsDesc': 'Encontre oportunidades de emprego',
    'dashboard.backHome': 'Voltar para Início',
    'dashboard.home': 'Início',
    'dashboard.settings': 'Configurações',
    'dashboard.admin': 'Painel Admin',
    'dashboard.errorProfile': 'Erro ao carregar perfil',
    'dashboard.errorPermissions': 'Erro ao verificar permissões',
    'dashboard.quickActions': 'Ações Rápidas',
    'dashboard.recentActivity': 'Atividade Recente',
    'dashboard.recommendations': 'Recomendações para Você',
    'dashboard.profileStrength': 'Força do Perfil',
    'dashboard.aiInsights': 'Insights de IA',
    
    // Settings
    'settings.title': 'Configurações',
    'settings.profile': 'Perfil',
    'settings.notifications': 'Notificações',
    'settings.privacy': 'Privacidade',
    'settings.security': 'Segurança',
    'settings.appearance': 'Aparência',
    'settings.personalInfo': 'Informações Pessoais',
    'settings.fullName': 'Nome Completo',
    'settings.email': 'E-mail',
    'settings.phone': 'Telefone',
    'settings.bio': 'Biografia',
    'settings.bioPlaceholder': 'Conte um pouco sobre você...',
    'settings.saveProfile': 'Salvar Perfil',
    'settings.profileUpdated': 'Perfil atualizado!',
    'settings.profileUpdateDesc': 'Suas informações foram salvas com sucesso.',
    'settings.notificationPrefs': 'Preferências de Notificação',
    'settings.emailNotifications': 'Notificações por E-mail',
    'settings.emailNotificationsDesc': 'Receba notificações importantes por e-mail',
    'settings.pushNotifications': 'Notificações Push',
    'settings.pushNotificationsDesc': 'Receba notificações em tempo real',
    'settings.weeklyReport': 'Relatório Semanal',
    'settings.weeklyReportDesc': 'Receba um resumo das suas atividades',
    'settings.courseUpdates': 'Atualizações de Cursos',
    'settings.courseUpdatesDesc': 'Novos cursos e materiais disponíveis',
    'settings.saveNotifications': 'Salvar Notificações',
    'settings.notificationsSaved': 'Preferências salvas!',
    'settings.notificationsSavedDesc': 'Suas configurações de notificação foram atualizadas.',
    'settings.privacySettings': 'Configurações de Privacidade',
    'settings.profileVisibility': 'Visibilidade do Perfil',
    'settings.public': 'Público',
    'settings.private': 'Privado',
    'settings.showEmail': 'Mostrar E-mail',
    'settings.showEmailDesc': 'Seu e-mail será visível no perfil',
    'settings.showPhone': 'Mostrar Telefone',
    'settings.showPhoneDesc': 'Seu telefone será visível no perfil',
    'settings.savePrivacy': 'Salvar Privacidade',
    'settings.privacyUpdated': 'Privacidade atualizada!',
    'settings.privacyUpdatedDesc': 'Suas configurações de privacidade foram salvas.',
    'settings.twoFactor': 'Autenticação em Dois Fatores (2FA)',
    'settings.twoFactorDesc': 'Adicione uma camada extra de segurança à sua conta',
    'settings.twoFactorEnabled': '2FA está ativado',
    'settings.twoFactorDisabled': '2FA está desativado',
    'settings.enable2FA': 'Ativar 2FA',
    'settings.disable2FA': 'Desativar 2FA',
    'settings.2FADisabled': '2FA Desativado',
    'settings.2FADisabledDesc': 'Autenticação em dois fatores foi desativada',
    'settings.error2FA': 'Falha ao desativar 2FA',
    'settings.themeSettings': 'Configurações de Tema',
    'settings.currentTheme': 'Tema Atual',
    'settings.themeToggle': 'Alternar Tema',
    
    // User Profile
    'profile.dashboard': 'Dashboard',
    'profile.settings': 'Configurações',
    'profile.logout': 'Sair',
    'profile.professional': 'Profissional',
    
    // Admin Panel
    'admin.title': 'Painel de Administração',
    'admin.description': 'Gerencie usuários e permissões',
    'admin.allUsers': 'Todos os Usuários',
    'admin.name': 'Nome',
    'admin.email': 'E-mail',
    'admin.role': 'Função',
    'admin.createdAt': 'Criado em',
    'admin.actions': 'Ações',
    'admin.noUsers': 'Nenhum usuário encontrado',
    'admin.deleteUser': 'Excluir Usuário',
    'admin.deleteConfirm': 'Tem certeza que deseja excluir este usuário?',
    'admin.deleteDesc': 'Esta ação não pode ser desfeita.',
    'admin.cancel': 'Cancelar',
    'admin.delete': 'Excluir',
    'admin.userDeleted': 'Usuário excluído',
    'admin.userDeletedDesc': 'O usuário foi removido com sucesso',
    'admin.errorDelete': 'Erro ao excluir usuário',
    'admin.errorFetch': 'Erro ao carregar usuários',
    'admin.admin': 'Admin',
    'admin.client': 'Cliente',
    
    // Demo Page
    'demo.title': 'NexusAI Demo',
    'demo.hero': 'Explore o Poder da',
    'demo.heroHighlight': ' IA ',
    'demo.heroEnd': 'no seu desenvolvimento profissional',
    'demo.heroDesc': 'Veja demonstrações interativas de como o NexusAI pode transformar sua carreira',
    'demo.watchDemo': 'Assistir Demo',
    'demo.howItWorks': 'Como Funciona',
    'demo.stepByStep': 'Passo a passo do processo',
    'demo.testimonials': 'O que nossos usuários dizem',
    'demo.cta.title': 'Pronto para transformar sua carreira?',
    'demo.cta.desc': 'Junte-se a milhares de profissionais que já estão usando o NexusAI',
    'demo.cta.start': 'Começar Gratuitamente',
    'demo.cta.learn': 'Saber Mais',
    'demo.resume.title': 'Otimização de Currículo',
    'demo.resume.desc': 'Veja como a IA analisa e melhora seu currículo em tempo real',
    'demo.resume.step1': 'Upload do seu currículo atual',
    'demo.resume.step2': 'Análise automática de pontos fortes e fracos',
    'demo.resume.step3': 'Sugestões de melhorias baseadas em IA',
    'demo.resume.step4': 'Geração de currículo otimizado em PDF',
    'demo.resume.stat1': 'Aumento médio na taxa de resposta',
    'demo.resume.stat2': 'Tempo médio de otimização',
    'demo.resume.stat3': 'Currículos otimizados',
    'demo.interview.title': 'Preparação para Entrevistas',
    'demo.interview.desc': 'Pratique com simulações realistas de entrevistas',
    'demo.interview.step1': 'Escolha o tipo de vaga desejada',
    'demo.interview.step2': 'Receba perguntas personalizadas',
    'demo.interview.step3': 'Grave suas respostas em tempo real',
    'demo.interview.step4': 'Obtenha feedback detalhado da IA',
    'demo.interview.stat1': 'Taxa de aprovação após treino',
    'demo.interview.stat2': 'Perguntas disponíveis',
    'demo.interview.stat3': 'Feedback personalizado',
    'demo.skills.title': 'Desenvolvimento de Habilidades',
    'demo.skills.desc': 'Aprimore suas competências com trilhas personalizadas',
    'demo.skills.step1': 'Avaliação inicial de competências',
    'demo.skills.step2': 'Trilha de aprendizado personalizada',
    'demo.skills.step3': 'Exercícios práticos e desafios',
    'demo.skills.step4': 'Certificados de conclusão',
    'demo.skills.stat1': 'Habilidades disponíveis',
    'demo.skills.stat2': 'Tempo médio de conclusão',
    'demo.skills.stat3': 'Taxa de satisfação',
  },
  en: {
    'nav.features': 'Features',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'auth.login': 'Login',
    'auth.signup': 'Sign Up',
    'auth.logout': 'Logout',
    'nav.dashboard': 'Dashboard',
    
    'hero.badge': 'AI-Powered Career Guidance',
    'hero.title': 'Your journey to the',
    'hero.titleHighlight': ' job market ',
    'hero.titleEnd': 'starts here',
    'hero.description': 'NexusAI is your intelligent assistant to find opportunities, improve your resume and land your dream job.',
    'hero.getStarted': 'Get Started',
    'hero.demo': 'View Demo',
    'hero.stat1': 'Guided Youth',
    'hero.stat2': 'Success Rate',
    'hero.stat3': 'AI Support',
    
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome back',
    'dashboard.welcomeBack': 'Welcome back',
    'dashboard.resume': 'Resume Optimizer',
    'dashboard.resumeDesc': 'Create and optimize your professional resume',
    'dashboard.interview': 'Interview Preparation',
    'dashboard.interviewDesc': 'Practice and prepare for your interviews',
    'dashboard.skills': 'Skills Development',
    'dashboard.skillsDesc': 'Enhance your professional competencies',
    'dashboard.jobs': 'Job Search',
    'dashboard.jobsDesc': 'Find job opportunities',
    'dashboard.backHome': 'Back to Home',
    'dashboard.home': 'Home',
    'dashboard.settings': 'Settings',
    'dashboard.admin': 'Admin Panel',
    'dashboard.errorProfile': 'Error loading profile',
    'dashboard.errorPermissions': 'Error checking permissions',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.recommendations': 'Recommendations for You',
    'dashboard.profileStrength': 'Profile Strength',
    'dashboard.aiInsights': 'AI Insights',
    
    'settings.title': 'Settings',
    'settings.profile': 'Profile',
    'settings.notifications': 'Notifications',
    'settings.privacy': 'Privacy',
    'settings.security': 'Security',
    'settings.appearance': 'Appearance',
    'settings.personalInfo': 'Personal Information',
    'settings.fullName': 'Full Name',
    'settings.email': 'Email',
    'settings.phone': 'Phone',
    'settings.bio': 'Bio',
    'settings.bioPlaceholder': 'Tell us about yourself...',
    'settings.saveProfile': 'Save Profile',
    'settings.profileUpdated': 'Profile updated!',
    'settings.profileUpdateDesc': 'Your information has been saved successfully.',
    'settings.notificationPrefs': 'Notification Preferences',
    'settings.emailNotifications': 'Email Notifications',
    'settings.emailNotificationsDesc': 'Receive important notifications via email',
    'settings.pushNotifications': 'Push Notifications',
    'settings.pushNotificationsDesc': 'Receive real-time notifications',
    'settings.weeklyReport': 'Weekly Report',
    'settings.weeklyReportDesc': 'Receive a summary of your activities',
    'settings.courseUpdates': 'Course Updates',
    'settings.courseUpdatesDesc': 'New courses and materials available',
    'settings.saveNotifications': 'Save Notifications',
    'settings.notificationsSaved': 'Preferences saved!',
    'settings.notificationsSavedDesc': 'Your notification settings have been updated.',
    'settings.privacySettings': 'Privacy Settings',
    'settings.profileVisibility': 'Profile Visibility',
    'settings.public': 'Public',
    'settings.private': 'Private',
    'settings.showEmail': 'Show Email',
    'settings.showEmailDesc': 'Your email will be visible on your profile',
    'settings.showPhone': 'Show Phone',
    'settings.showPhoneDesc': 'Your phone will be visible on your profile',
    'settings.savePrivacy': 'Save Privacy',
    'settings.privacyUpdated': 'Privacy updated!',
    'settings.privacyUpdatedDesc': 'Your privacy settings have been saved.',
    'settings.twoFactor': 'Two-Factor Authentication (2FA)',
    'settings.twoFactorDesc': 'Add an extra layer of security to your account',
    'settings.twoFactorEnabled': '2FA is enabled',
    'settings.twoFactorDisabled': '2FA is disabled',
    'settings.enable2FA': 'Enable 2FA',
    'settings.disable2FA': 'Disable 2FA',
    'settings.2FADisabled': '2FA Disabled',
    'settings.2FADisabledDesc': 'Two-factor authentication has been disabled',
    'settings.error2FA': 'Failed to disable 2FA',
    'settings.themeSettings': 'Theme Settings',
    'settings.currentTheme': 'Current Theme',
    'settings.themeToggle': 'Toggle Theme',
    
    'profile.dashboard': 'Dashboard',
    'profile.settings': 'Settings',
    'profile.logout': 'Logout',
    'profile.professional': 'Professional',
    
    'admin.title': 'Administration Panel',
    'admin.description': 'Manage users and permissions',
    'admin.allUsers': 'All Users',
    'admin.name': 'Name',
    'admin.email': 'Email',
    'admin.role': 'Role',
    'admin.createdAt': 'Created at',
    'admin.actions': 'Actions',
    'admin.noUsers': 'No users found',
    'admin.deleteUser': 'Delete User',
    'admin.deleteConfirm': 'Are you sure you want to delete this user?',
    'admin.deleteDesc': 'This action cannot be undone.',
    'admin.cancel': 'Cancel',
    'admin.delete': 'Delete',
    'admin.userDeleted': 'User deleted',
    'admin.userDeletedDesc': 'User has been removed successfully',
    'admin.errorDelete': 'Error deleting user',
    'admin.errorFetch': 'Error loading users',
    'admin.admin': 'Admin',
    'admin.client': 'Client',
    
    'demo.title': 'NexusAI Demo',
    'demo.hero': 'Explore the Power of',
    'demo.heroHighlight': ' AI ',
    'demo.heroEnd': 'in your professional development',
    'demo.heroDesc': 'See interactive demonstrations of how NexusAI can transform your career',
    'demo.watchDemo': 'Watch Demo',
    'demo.howItWorks': 'How It Works',
    'demo.stepByStep': 'Step by step process',
    'demo.testimonials': 'What our users say',
    'demo.cta.title': 'Ready to transform your career?',
    'demo.cta.desc': 'Join thousands of professionals already using NexusAI',
    'demo.cta.start': 'Start Free',
    'demo.cta.learn': 'Learn More',
    'demo.resume.title': 'Resume Optimization',
    'demo.resume.desc': 'See how AI analyzes and improves your resume in real time',
    'demo.resume.step1': 'Upload your current resume',
    'demo.resume.step2': 'Automatic analysis of strengths and weaknesses',
    'demo.resume.step3': 'AI-based improvement suggestions',
    'demo.resume.step4': 'Generate optimized resume in PDF',
    'demo.resume.stat1': 'Average increase in response rate',
    'demo.resume.stat2': 'Average optimization time',
    'demo.resume.stat3': 'Optimized resumes',
    'demo.interview.title': 'Interview Preparation',
    'demo.interview.desc': 'Practice with realistic interview simulations',
    'demo.interview.step1': 'Choose the desired job type',
    'demo.interview.step2': 'Receive personalized questions',
    'demo.interview.step3': 'Record your answers in real time',
    'demo.interview.step4': 'Get detailed AI feedback',
    'demo.interview.stat1': 'Approval rate after training',
    'demo.interview.stat2': 'Available questions',
    'demo.interview.stat3': 'Personalized feedback',
    'demo.skills.title': 'Skills Development',
    'demo.skills.desc': 'Improve your skills with personalized tracks',
    'demo.skills.step1': 'Initial skills assessment',
    'demo.skills.step2': 'Personalized learning path',
    'demo.skills.step3': 'Practical exercises and challenges',
    'demo.skills.step4': 'Completion certificates',
    'demo.skills.stat1': 'Available skills',
    'demo.skills.stat2': 'Average completion time',
    'demo.skills.stat3': 'Satisfaction rate',
  },
  es: {
    'nav.features': 'Características',
    'nav.about': 'Acerca de',
    'nav.contact': 'Contacto',
    'auth.login': 'Iniciar sesión',
    'auth.signup': 'Registrarse',
    'auth.logout': 'Cerrar sesión',
    'nav.dashboard': 'Panel',
    
    'hero.badge': 'Orientación Profesional con IA',
    'hero.title': 'Tu viaje hacia el',
    'hero.titleHighlight': ' mercado laboral ',
    'hero.titleEnd': 'comienza aquí',
    'hero.description': 'NexusAI es tu asistente inteligente para encontrar oportunidades, mejorar tu currículum y conseguir el trabajo de tus sueños.',
    'hero.getStarted': 'Comenzar Ahora',
    'hero.demo': 'Ver Demostración',
    'hero.stat1': 'Jóvenes Orientados',
    'hero.stat2': 'Tasa de Éxito',
    'hero.stat3': 'Soporte IA',
    
    'dashboard.title': 'Panel de Control',
    'dashboard.welcome': 'Bienvenido de nuevo',
    'dashboard.welcomeBack': 'Bienvenido de nuevo',
    'dashboard.resume': 'Optimizar Currículum',
    'dashboard.resumeDesc': 'Crea y optimiza tu currículum profesional',
    'dashboard.interview': 'Preparación para Entrevistas',
    'dashboard.interviewDesc': 'Practica y prepárate para tus entrevistas',
    'dashboard.skills': 'Desarrollo de Habilidades',
    'dashboard.skillsDesc': 'Mejora tus competencias profesionales',
    'dashboard.jobs': 'Buscar Empleos',
    'dashboard.jobsDesc': 'Encuentra oportunidades de empleo',
    'dashboard.backHome': 'Volver al Inicio',
    'dashboard.home': 'Inicio',
    'dashboard.settings': 'Configuración',
    'dashboard.admin': 'Panel Admin',
    'dashboard.errorProfile': 'Error al cargar perfil',
    'dashboard.errorPermissions': 'Error al verificar permisos',
    'dashboard.quickActions': 'Acciones Rápidas',
    'dashboard.recentActivity': 'Actividad Reciente',
    'dashboard.recommendations': 'Recomendaciones para Ti',
    'dashboard.profileStrength': 'Fortaleza del Perfil',
    'dashboard.aiInsights': 'Perspectivas de IA',
    
    'settings.title': 'Configuración',
    'settings.profile': 'Perfil',
    'settings.notifications': 'Notificaciones',
    'settings.privacy': 'Privacidad',
    'settings.security': 'Seguridad',
    'settings.appearance': 'Apariencia',
    'settings.personalInfo': 'Información Personal',
    'settings.fullName': 'Nombre Completo',
    'settings.email': 'Correo Electrónico',
    'settings.phone': 'Teléfono',
    'settings.bio': 'Biografía',
    'settings.bioPlaceholder': 'Cuéntanos sobre ti...',
    'settings.saveProfile': 'Guardar Perfil',
    'settings.profileUpdated': '¡Perfil actualizado!',
    'settings.profileUpdateDesc': 'Tu información ha sido guardada exitosamente.',
    'settings.notificationPrefs': 'Preferencias de Notificación',
    'settings.emailNotifications': 'Notificaciones por Correo',
    'settings.emailNotificationsDesc': 'Recibe notificaciones importantes por correo',
    'settings.pushNotifications': 'Notificaciones Push',
    'settings.pushNotificationsDesc': 'Recibe notificaciones en tiempo real',
    'settings.weeklyReport': 'Informe Semanal',
    'settings.weeklyReportDesc': 'Recibe un resumen de tus actividades',
    'settings.courseUpdates': 'Actualizaciones de Cursos',
    'settings.courseUpdatesDesc': 'Nuevos cursos y materiales disponibles',
    'settings.saveNotifications': 'Guardar Notificaciones',
    'settings.notificationsSaved': '¡Preferencias guardadas!',
    'settings.notificationsSavedDesc': 'Tu configuración de notificación ha sido actualizada.',
    'settings.privacySettings': 'Configuración de Privacidad',
    'settings.profileVisibility': 'Visibilidad del Perfil',
    'settings.public': 'Público',
    'settings.private': 'Privado',
    'settings.showEmail': 'Mostrar Correo',
    'settings.showEmailDesc': 'Tu correo será visible en tu perfil',
    'settings.showPhone': 'Mostrar Teléfono',
    'settings.showPhoneDesc': 'Tu teléfono será visible en tu perfil',
    'settings.savePrivacy': 'Guardar Privacidad',
    'settings.privacyUpdated': '¡Privacidad actualizada!',
    'settings.privacyUpdatedDesc': 'Tu configuración de privacidad ha sido guardada.',
    'settings.twoFactor': 'Autenticación de Dos Factores (2FA)',
    'settings.twoFactorDesc': 'Agrega una capa extra de seguridad a tu cuenta',
    'settings.twoFactorEnabled': '2FA está activado',
    'settings.twoFactorDisabled': '2FA está desactivado',
    'settings.enable2FA': 'Activar 2FA',
    'settings.disable2FA': 'Desactivar 2FA',
    'settings.2FADisabled': '2FA Desactivado',
    'settings.2FADisabledDesc': 'Autenticación de dos factores ha sido desactivada',
    'settings.error2FA': 'Fallo al desactivar 2FA',
    'settings.themeSettings': 'Configuración de Tema',
    'settings.currentTheme': 'Tema Actual',
    'settings.themeToggle': 'Cambiar Tema',
    
    'profile.dashboard': 'Panel',
    'profile.settings': 'Configuración',
    'profile.logout': 'Cerrar Sesión',
    'profile.professional': 'Profesional',
    
    'admin.title': 'Panel de Administración',
    'admin.description': 'Gestionar usuarios y permisos',
    'admin.allUsers': 'Todos los Usuarios',
    'admin.name': 'Nombre',
    'admin.email': 'Correo',
    'admin.role': 'Rol',
    'admin.createdAt': 'Creado en',
    'admin.actions': 'Acciones',
    'admin.noUsers': 'No se encontraron usuarios',
    'admin.deleteUser': 'Eliminar Usuario',
    'admin.deleteConfirm': '¿Estás seguro de que deseas eliminar este usuario?',
    'admin.deleteDesc': 'Esta acción no se puede deshacer.',
    'admin.cancel': 'Cancelar',
    'admin.delete': 'Eliminar',
    'admin.userDeleted': 'Usuario eliminado',
    'admin.userDeletedDesc': 'El usuario ha sido eliminado exitosamente',
    'admin.errorDelete': 'Error al eliminar usuario',
    'admin.errorFetch': 'Error al cargar usuarios',
    'admin.admin': 'Admin',
    'admin.client': 'Cliente',
  },
  fr: {
    'nav.features': 'Fonctionnalités',
    'nav.about': 'À propos',
    'nav.contact': 'Contact',
    'auth.login': 'Connexion',
    'auth.signup': "S'inscrire",
    'auth.logout': 'Déconnexion',
    'nav.dashboard': 'Tableau de bord',
    
    'hero.badge': 'Orientation Professionnelle par IA',
    'hero.title': 'Votre voyage vers le',
    'hero.titleHighlight': ' marché du travail ',
    'hero.titleEnd': 'commence ici',
    'hero.description': "NexusAI est votre assistant intelligent pour trouver des opportunités, améliorer votre CV et décrocher l'emploi de vos rêves.",
    'hero.getStarted': 'Commencer',
    'hero.demo': 'Voir la Démo',
    'hero.stat1': 'Jeunes Guidés',
    'hero.stat2': 'Taux de Réussite',
    'hero.stat3': 'Support IA',
    
    'dashboard.title': 'Tableau de bord',
    'dashboard.welcome': 'Bon retour',
    'dashboard.resume': 'Optimiser le CV',
    'dashboard.resumeDesc': 'Créez et optimisez votre CV professionnel',
    'dashboard.interview': 'Préparation aux Entretiens',
    'dashboard.interviewDesc': 'Pratiquez et préparez-vous pour vos entretiens',
    'dashboard.skills': 'Développement des Compétences',
    'dashboard.skillsDesc': 'Améliorez vos compétences professionnelles',
    'dashboard.backHome': "Retour à l'Accueil",
  },
  de: {
    'nav.features': 'Funktionen',
    'nav.about': 'Über uns',
    'nav.contact': 'Kontakt',
    'auth.login': 'Anmelden',
    'auth.signup': 'Registrieren',
    'auth.logout': 'Abmelden',
    'nav.dashboard': 'Dashboard',
    
    'hero.badge': 'KI-gestützte Berufsberatung',
    'hero.title': 'Ihre Reise zum',
    'hero.titleHighlight': ' Arbeitsmarkt ',
    'hero.titleEnd': 'beginnt hier',
    'hero.description': 'NexusAI ist Ihr intelligenter Assistent, um Chancen zu finden, Ihren Lebenslauf zu verbessern und Ihren Traumjob zu bekommen.',
    'hero.getStarted': 'Jetzt Starten',
    'hero.demo': 'Demo Ansehen',
    'hero.stat1': 'Begleitete Jugendliche',
    'hero.stat2': 'Erfolgsquote',
    'hero.stat3': 'KI-Support',
    
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Willkommen zurück',
    'dashboard.resume': 'Lebenslauf Optimieren',
    'dashboard.resumeDesc': 'Erstellen und optimieren Sie Ihren professionellen Lebenslauf',
    'dashboard.interview': 'Vorstellungsgesprächsvorbereitung',
    'dashboard.interviewDesc': 'Üben und bereiten Sie sich auf Ihre Vorstellungsgespräche vor',
    'dashboard.skills': 'Kompetenzentwicklung',
    'dashboard.skillsDesc': 'Verbessern Sie Ihre beruflichen Kompetenzen',
    'dashboard.backHome': 'Zurück zur Startseite',
  },
  it: {
    'nav.features': 'Caratteristiche',
    'nav.about': 'Chi siamo',
    'nav.contact': 'Contatto',
    'auth.login': 'Accedi',
    'auth.signup': 'Registrati',
    'auth.logout': 'Esci',
    'nav.dashboard': 'Pannello',
    
    'hero.badge': 'Orientamento Professionale con IA',
    'hero.title': 'Il tuo viaggio verso il',
    'hero.titleHighlight': ' mercato del lavoro ',
    'hero.titleEnd': 'inizia qui',
    'hero.description': "NexusAI è il tuo assistente intelligente per trovare opportunità, migliorare il tuo curriculum e ottenere il lavoro dei tuoi sogni.",
    'hero.getStarted': 'Inizia Ora',
    'hero.demo': 'Vedi Demo',
    'hero.stat1': 'Giovani Guidati',
    'hero.stat2': 'Tasso di Successo',
    'hero.stat3': 'Supporto IA',
    
    'dashboard.title': 'Pannello di Controllo',
    'dashboard.welcome': 'Bentornato',
    'dashboard.resume': 'Ottimizza Curriculum',
    'dashboard.resumeDesc': 'Crea e ottimizza il tuo curriculum professionale',
    'dashboard.interview': 'Preparazione ai Colloqui',
    'dashboard.interviewDesc': 'Pratica e preparati per i tuoi colloqui',
    'dashboard.skills': 'Sviluppo delle Competenze',
    'dashboard.skillsDesc': 'Migliora le tue competenze professionali',
    'dashboard.backHome': "Torna all'Inizio",
  },
  zh: {
    'nav.features': '功能',
    'nav.about': '关于',
    'nav.contact': '联系',
    'auth.login': '登录',
    'auth.signup': '注册',
    'auth.logout': '退出',
    'nav.dashboard': '仪表板',
    
    'hero.badge': 'AI驱动的职业指导',
    'hero.title': '您的',
    'hero.titleHighlight': ' 职场之旅 ',
    'hero.titleEnd': '从这里开始',
    'hero.description': 'NexusAI是您的智能助手，帮助您找到机会、改善简历并获得理想的工作。',
    'hero.getStarted': '立即开始',
    'hero.demo': '查看演示',
    'hero.stat1': '指导的年轻人',
    'hero.stat2': '成功率',
    'hero.stat3': 'AI支持',
    
    'dashboard.title': '仪表板',
    'dashboard.welcome': '欢迎回来',
    'dashboard.resume': '优化简历',
    'dashboard.resumeDesc': '创建并优化您的专业简历',
    'dashboard.interview': '面试准备',
    'dashboard.interviewDesc': '练习并为您的面试做好准备',
    'dashboard.skills': '技能发展',
    'dashboard.skillsDesc': '提升您的专业能力',
    'dashboard.backHome': '返回首页',
  },
  ja: {
    'nav.features': '機能',
    'nav.about': '概要',
    'nav.contact': 'お問い合わせ',
    'auth.login': 'ログイン',
    'auth.signup': '登録',
    'auth.logout': 'ログアウト',
    'nav.dashboard': 'ダッシュボード',
    
    'hero.badge': 'AIによるキャリアガイダンス',
    'hero.title': 'あなたの',
    'hero.titleHighlight': ' 就職活動 ',
    'hero.titleEnd': 'はここから始まります',
    'hero.description': 'NexusAIは、機会を見つけ、履歴書を改善し、夢の仕事を獲得するためのインテリジェントなアシスタントです。',
    'hero.getStarted': '今すぐ始める',
    'hero.demo': 'デモを見る',
    'hero.stat1': '指導された若者',
    'hero.stat2': '成功率',
    'hero.stat3': 'AIサポート',
    
    'dashboard.title': 'ダッシュボード',
    'dashboard.welcome': 'おかえりなさい',
    'dashboard.resume': '履歴書の最適化',
    'dashboard.resumeDesc': 'プロフェッショナルな履歴書を作成し最適化',
    'dashboard.interview': '面接準備',
    'dashboard.interviewDesc': '面接の練習と準備',
    'dashboard.skills': 'スキル開発',
    'dashboard.skillsDesc': '専門的な能力を向上させる',
    'dashboard.backHome': 'ホームに戻る',
  },
  ko: {
    'nav.features': '기능',
    'nav.about': '소개',
    'nav.contact': '연락처',
    'auth.login': '로그인',
    'auth.signup': '가입',
    'auth.logout': '로그아웃',
    'nav.dashboard': '대시보드',
    
    'hero.badge': 'AI 기반 커리어 가이던스',
    'hero.title': '당신의',
    'hero.titleHighlight': ' 취업 여정 ',
    'hero.titleEnd': '이 여기서 시작됩니다',
    'hero.description': 'NexusAI는 기회를 찾고, 이력서를 개선하며, 꿈의 직장을 얻기 위한 지능형 도우미입니다.',
    'hero.getStarted': '시작하기',
    'hero.demo': '데모 보기',
    'hero.stat1': '지도된 청년',
    'hero.stat2': '성공률',
    'hero.stat3': 'AI 지원',
    
    'dashboard.title': '대시보드',
    'dashboard.welcome': '다시 오신 것을 환영합니다',
    'dashboard.resume': '이력서 최적화',
    'dashboard.resumeDesc': '전문 이력서 작성 및 최적화',
    'dashboard.interview': '면접 준비',
    'dashboard.interviewDesc': '면접 연습 및 준비',
    'dashboard.skills': '스킬 개발',
    'dashboard.skillsDesc': '전문 역량 향상',
    'dashboard.backHome': '홈으로 돌아가기',
  },
  ru: {
    'nav.features': 'Функции',
    'nav.about': 'О нас',
    'nav.contact': 'Контакты',
    'auth.login': 'Войти',
    'auth.signup': 'Регистрация',
    'auth.logout': 'Выйти',
    'nav.dashboard': 'Панель',
    
    'hero.badge': 'Карьерное руководство с ИИ',
    'hero.title': 'Ваше путешествие к',
    'hero.titleHighlight': ' рынку труда ',
    'hero.titleEnd': 'начинается здесь',
    'hero.description': 'NexusAI - ваш интеллектуальный помощник для поиска возможностей, улучшения резюме и получения работы мечты.',
    'hero.getStarted': 'Начать сейчас',
    'hero.demo': 'Смотреть демо',
    'hero.stat1': 'Наставленная молодежь',
    'hero.stat2': 'Процент успеха',
    'hero.stat3': 'Поддержка ИИ',
    
    'dashboard.title': 'Панель управления',
    'dashboard.welcome': 'Добро пожаловать',
    'dashboard.resume': 'Оптимизация резюме',
    'dashboard.resumeDesc': 'Создайте и оптимизируйте свое профессиональное резюме',
    'dashboard.interview': 'Подготовка к собеседованию',
    'dashboard.interviewDesc': 'Практикуйтесь и готовьтесь к собеседованиям',
    'dashboard.skills': 'Развитие навыков',
    'dashboard.skillsDesc': 'Улучшите свои профессиональные компетенции',
    'dashboard.backHome': 'Вернуться на главную',
  },
  ar: {
    'nav.features': 'الميزات',
    'nav.about': 'عن',
    'nav.contact': 'اتصل',
    'auth.login': 'تسجيل الدخول',
    'auth.signup': 'التسجيل',
    'auth.logout': 'تسجيل الخروج',
    'nav.dashboard': 'لوحة التحكم',
    
    'hero.badge': 'التوجيه المهني بالذكاء الاصطناعي',
    'hero.title': 'رحلتك إلى',
    'hero.titleHighlight': ' سوق العمل ',
    'hero.titleEnd': 'تبدأ هنا',
    'hero.description': 'NexusAI هو مساعدك الذكي للعثور على الفرص وتحسين سيرتك الذاتية والحصول على وظيفة أحلامك.',
    'hero.getStarted': 'ابدأ الآن',
    'hero.demo': 'عرض التجريبي',
    'hero.stat1': 'الشباب الموجهين',
    'hero.stat2': 'معدل النجاح',
    'hero.stat3': 'دعم الذكاء الاصطناعي',
    
    'dashboard.title': 'لوحة التحكم',
    'dashboard.welcome': 'مرحبا بعودتك',
    'dashboard.resume': 'تحسين السيرة الذاتية',
    'dashboard.resumeDesc': 'إنشاء وتحسين سيرتك الذاتية المهنية',
    'dashboard.interview': 'الإعداد للمقابلات',
    'dashboard.interviewDesc': 'ممارسة والاستعداد لمقابلاتك',
    'dashboard.skills': 'تطوير المهارات',
    'dashboard.skillsDesc': 'تعزيز كفاءاتك المهنية',
    'dashboard.backHome': 'العودة إلى الصفحة الرئيسية',
  },
  hi: {
    'nav.features': 'विशेषताएं',
    'nav.about': 'के बारे में',
    'nav.contact': 'संपर्क',
    'auth.login': 'लॉगिन',
    'auth.signup': 'साइन अप',
    'auth.logout': 'लॉगआउट',
    'nav.dashboard': 'डैशबोर्ड',
    
    'hero.badge': 'AI-संचालित करियर मार्गदर्शन',
    'hero.title': 'आपकी यात्रा',
    'hero.titleHighlight': ' नौकरी बाजार ',
    'hero.titleEnd': 'यहाँ से शुरू होती है',
    'hero.description': 'NexusAI आपका बुद्धिमान सहायक है अवसर खोजने, अपना रिज्यूमे सुधारने और अपनी सपनों की नौकरी पाने के लिए।',
    'hero.getStarted': 'अभी शुरू करें',
    'hero.demo': 'डेमो देखें',
    'hero.stat1': 'मार्गदर्शित युवा',
    'hero.stat2': 'सफलता दर',
    'hero.stat3': 'AI सहायता',
    
    'dashboard.title': 'डैशबोर्ड',
    'dashboard.welcome': 'वापसी पर स्वागत है',
    'dashboard.resume': 'रिज्यूमे अनुकूलन',
    'dashboard.resumeDesc': 'अपना पेशेवर रिज्यूमे बनाएं और अनुकूलित करें',
    'dashboard.interview': 'साक्षात्कार की तैयारी',
    'dashboard.interviewDesc': 'अपने साक्षात्कार के लिए अभ्यास और तैयारी करें',
    'dashboard.skills': 'कौशल विकास',
    'dashboard.skillsDesc': 'अपनी पेशेवर क्षमताओं को बढ़ाएं',
    'dashboard.backHome': 'होम पर वापस जाएं',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'pt';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
    // Set direction for RTL languages
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};