// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmtmyjxnixujqvoltzia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtdG15anhuaXh1anF2b2x0emlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNzk0MjcsImV4cCI6MjA3Mzg1NTQyN30.fs8N_VKHhSVM3AWyqWf-sTX3bYyP19QmVAs9O5z3xsw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});